### ISSUE TITLE
Parse_date raise ParseError("Expecting a string %r" % datestring)

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-api-client-python#36]
* As root install manageiq-client-api libirary.

```
yum install -y python-pip
pip install git+https://github.com/ManageIQ/manageiq-api-client-python.git
```

* miq server version tested.
  * Master branch using API 
```
commit 74e132dab2284a5d0fe3ab252b80ee6c54e94a66
Merge: 83a24ce 5dc0375
Author: Brandon Dunne <brandondunne@hotmail.com>
Date:   Fri Feb 2 16:38:11 2018 -0500

    Merge pull request #16944 from bmclaughlin/add-missing-flavor-string

    Fix filename when downloading pdf from Flavor summary

```

* example.py

```
[me@miqwk02 manageiq-client]$ python ./example.py

import os
from manageiq_client.api import ManageIQClient as MiqApi

url = os.environ.get('MIQURL') or 'http://localhost:3000/api'
username = os.environ.get('MIQUSERNAME') or 'admin'
password = os.environ.get('MIQPASSWORD') or 'smartvm'
token = os.environ.get('MIQTOKEN')

client = None

if token:
    print("\nAuthenticating with the API token")
    client = MiqApi(url, dict(token=token))
else:
    print("\nAuthenticating with the user credentials: "+username+" / "+password)
    client = MiqApi(url, dict(user=username, password=password))

print("\nManageIQ version: {0}".format(client.version))
print("\nVirtual Machines Collection\n")

for vm in client.collections.vms.all:
    print(vm.name)

```
* Error message

```
[me@miqwk02 manageiq-client]$ python ./example.py

Authenticating with the user credentials: admin / smartvm

ManageIQ version: 4.0.0-pre

Virtual Machines Collection

Traceback (most recent call last):
  File "./example.py", line 21, in <module>
    for vm in client.collections.vms.all:
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 351, in all
    return [Entity(self, r) for r in self._resources]
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 408, in __init__
    self._load_data()
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 412, in _load_data
    self.reload(get=False)
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 442, in reload
    setattr(self, key, iso8601.parse_date(value))
  File "/usr/lib/python2.7/site-packages/iso8601/iso8601.py", line 192, in parse_date
    raise ParseError("Expecting a string %r" % datestring)
iso8601.iso8601.ParseError: Expecting a string None
[me@miqwk02 manageiq-client]$

```

**Comment by mkoura** [comment]
Fixed by https://github.com/ManageIQ/manageiq-api-client-python/pull/39 that is already released in [v0.4.1](https://github.com/ManageIQ/manageiq-api-client-python/releases/tag/v0.4.1)
