### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', error(97, 'Address family not supported by protocol'))

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-api-client-python#37]
* miq test server running fine-4:

```
hostname = miq01.test.com

commit a5e507b055d7bbd623d8994e5139b2d53dd77f45
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Tue Oct 24 16:16:44 2017 -0400

    Release fine-4

```

* example.py

All following manageiq_client.api test are running from same host on miq01.test.com.

```
[me@manageiq-client]$ cat  ./example.py
import os
from manageiq_client.api import ManageIQClient as MiqApi

url = os.environ.get('MIQURL') or 'http://localhost:3000/api'
username = os.environ.get('MIQUSERNAME') or 'admin'
password = os.environ.get('MIQPASSWORD') or 'smartvm'
token = os.environ.get('MIQTOKEN')

client = None

if token:
    print("\nAuthenticating with the API token")
    client = MiqApi(url, dict(token=token))
else:
    print("\nAuthenticating with the user credentials: "+username+" / "+password)
    client = MiqApi(url, dict(user=username, password=password))

print("\nManageIQ version: {0}".format(client.version))
print("\nVirtual Machines Collection\n")

for vm in client.collections.vms.all:
    print(vm.name)
[me@manageiq-client]$

```

* Error message

```
[me@manageiq-client]$python ./example.py

Authenticating with the user credentials: admin / smartvm

ManageIQ version: 2.4.0

Virtual Machines Collection

Traceback (most recent call last):
  File "./example.py", line 21, in <module>
    for vm in client.collections.vms.all:
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 350, in all
    self.reload(expand=True)
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 280, in reload
    self._data = self._api.get(self._href, **kwargs)
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 111, in get
    partial(self._session.get, url, params=get_params))
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 106, in _sending_request
    raise last_connection_exception
requests.exceptions.ConnectionError: ('Connection aborted.', error(97, 'Address family not supported by protocol'))
[me@manageiq-client]$
```

*   curl -4 http://localhost:3000
ipv4 works.

```
<snipped>
<script>
  miqGetTZO();
  miqGetBrowserInfo();
  miqTreeClearState();
</script>

<script>
  API.logout();
  delete localStorage['patternfly-navigation-secondary'];
  delete localStorage['patternfly-navigation-tertiary'];
  miqFlashClearSaved();
</script>
</body>
</html>
<snipped>
```

* curl -6 http://localhost:3000 

miq01 doesn't have IPV6 enabled. 

```
[me@miq01 manageiq-client]$  curl -6 http://localhost:3000
curl: (6) Couldn't resolve host 'localhost'
[me@miq01 manageiq-client]$ grep  localhost /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
[me@miq01 manageiq-client]$
# switch to root
[root@miq01 ~]# ping ::1
ping: ::1: Address family for hostname not supported
[root@miq01 ~]# ping -c 1 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.025 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.025/0.025/0.025/0.000 ms
[root@miq01 ~]#

```

*  query on http://127.0.0.1:3000/api

```
[me@miq01 manageiq-client]$ python  example-127.0.0.1.py

Authenticating with the user credentials: admin / smartvm

ManageIQ version: 2.4.0

Virtual Machines Collection

Traceback (most recent call last):
  File "example-127.0.0.1.py", line 21, in <module>
    for vm in client.collections.vms.all:
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 350, in all
    self.reload(expand=True)
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 280, in reload
    self._data = self._api.get(self._href, **kwargs)
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 111, in get
    partial(self._session.get, url, params=get_params))
  File "/usr/lib/python2.7/site-packages/manageiq_client/api.py", line 106, in _sending_request
    raise last_connection_exception
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
[me@miq01 manageiq-client]$ grep 127.0.0.1  example-127.0.0.1.py
url = os.environ.get('MIQURL') or 'http://127.0.0.1:3000/api'
[me@miq01 manageiq-client]$
```

**Comment by cben** [comment]
Can you show the actual URL used?  Was it `http://localhost:3000/api`?
Smells like IPv4 / IPv6.  (we definitely want IPv6 to work! just trying to narrow down...)
If it's `localhost`:
1. does `curl -4 http://localhost:3000` and `curl -6 http://localhost:3000` work?
2. can you try `http://127.0.0.1:3000/api` with manageiq_client?
    you might need to run server as `rails server -b 127.0.0.1 -p 3000` for it to accept `Host: 127.0.0.1` requests (?).

**Comment by tjyang** [comment]
@cben , I updated  issues with answer of you questions you requested.  Let me know if you need more info.
 
Looks like the new manageiq client api by default is trying to interact  with ipv6 at someplace.  At earlier version of manageiq_client.api python library, I was able to list out all VMs on miq01.test.com machine even with IPV6 disabled.

**Comment by tjyang** [comment]
@cben , can you provide an example command to run the [test cases](https://github.com/ManageIQ/manageiq-api-client-python/tree/master/testing) ?

**Comment by cben** [comment]
Thanks.  The "connection refused" means you do need the `-b 127.0.0.1` on the server, can you retry with that?
Also, if you comment out ::1 from /etc/hosts, will then localhost:3000 work?

**Comment by tjyang** [comment]
*  You said: The "connection refused" means you do need the -b 127.0.0.1 on the server" 
   * by default miq01 is already listening on 127.0.0.1:3000 , see below
   ```
   [root@miq01 vmdb]# netstat -antulp |grep 3000
   tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      15293/puma 3.3.0 (t
   [root@miq01 vmdb]#
   ```

   *  Following command exit since port 3000 is already be used.
```
[root@miq01 vmdb]# bin/rails server -b 127.0.0.1 -p 3000
=> Booting Puma
=> Rails 5.0.6 application starting in production on http://127.0.0.1:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.3.0 (ruby 2.3.1-p112), codename: Jovial Platypus
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://127.0.0.1:3000
Exiting
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.3.0/lib/puma/binder.rb:255:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.3.0/lib/puma/binder.rb:255:in `new'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.3.0/lib/puma/binder.rb:255:in `add_tcp_listener'

```
 * Your 2nd question: "if you comment out ::1 from /etc/hosts, will then localhost:3000 work?"

```
[me@miq01 ]$ grep ::1 /etc/hosts
#::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
[me@miq01 ]$

# following command still work with ::1 line commented out
 curl -4 http://localhost:3000 ;echo $?
```

**Comment by mfeifer** [comment]
@mshriver can you please take a look?

**Comment by tjyang** [comment]
Hi @mfeifer 

I think this ticket can  be resolved.

* the example.py, MIQ and OS info.
```
(venv) [tjyang@miqregion01 ~]$ vmdb
(venv) [tjyang@miqregion01 vmdb]$ cat VERSION;echo ;cat /etc/redhat-release
ivanchuk-1
CentOS Linux release 7.7.1908 (Core)
(venv) [tjyang@miqregion01 vmdb]$
(venv) [tjyang@miqregion01 ~]$ cat example.py
import os
from manageiq_client.api import ManageIQClient as MiqApi

url = os.environ.get('MIQURL') or 'http://localhost:3000/api'
username = os.environ.get('MIQUSERNAME') or 'admin'
password = os.environ.get('MIQPASSWORD') or 'smartvm'
token = os.environ.get('MIQTOKEN')

client = None

if token:
    print("\nAuthenticating with the API token")
    client = MiqApi(url, dict(token=token))
else:
    print("\nAuthenticating with the user credentials: "+username+" / "+password)
    client = MiqApi(url, dict(user=username, password=password))

print("\nManageIQ version: {0}".format(client.version))
print("\nVirtual Machines Collection\n")

for vm in client.collections.vms.all:
    print(vm.name)
(venv) [tjyang@miqregion01 ~]$

```
* test result
```
(venv) [tjyang@miqregion01 ~]$ python example.py

Authenticating with the user credentials: admin / smartvm

ManageIQ version: 4.1.0

Virtual Machines Collection

test01
miq01
rdo01
gitlab
awx02
<snipped>
miqregion01
(venv) [tjyang@miqregion01 ~]$
```
